### ISSUE TITLE
Unverified HTTPS request is being made to host 'www.nseindia.com'

### ISSUE THREAD

**Issue by warriorx86** [Bharadwajharii/Web-Scrape-live-option-chain-from-NSE#1]
Hi Newbie here. I am getting. Warning (from warnings module):
  File "C:\Users\Prakash Dresses\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\urllib3\connectionpool.py", line 1013
    warnings.warn(
InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.nseindia.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
![python](https://user-images.githubusercontent.com/40427773/115986540-4ab2a600-a5ce-11eb-9b8a-5d5e15995807.png)

how to bypass this

**Comment by Bharadwajharii** [comment]
Are you getting a empty dataframe  'data1' or is it populated

**Comment by Bharadwajharii** [comment]
Try adding below code to ignore warning 

`from datetime import datetime`
`from requests.packages.urllib3.exceptions import InsecureRequestWarning`

**Comment by Bharadwajharii** [comment]
Due to inactivity I am closing this issue.
